### PR TITLE
Persistent frostdb with WAL and local bucket store

### PR DESCRIPTION
**Pull request by arajkumar**
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>

### CODE REVIEW

**Comment by arajkumar** [comment]
It fails with the following error when I enable bucket storage based on local filesystem.
```
ts=2022-08-16T06:05:47.665Z caller=main.go:1113 level=error err="opening storage failed: first WAL replay: read index 0: not found"
```
@thorfour Is it bucket storage and WAL are mutually exclusive[1]?


[1] https://github.com/polarsignals/frostdb/blob/6169cce4d9d446524f5e25e99ab51780184451fd/db.go#L444-L459

**Comment by thorfour** [comment]
hmm they shouldn't be, but if we do successfully write the storage we should remove the WAL maybe that interaction is part of the problem?

**Comment by arajkumar** [comment]
@thorfour There is a problem with WAL handling in frostdb, fixed it in https://github.com/polarsignals/frostdb/pull/163.

**Comment by thorfour** [comment]
Oh awesome! Thank you

**Comment by arajkumar** [comment]
@thorfour All issues with WAL and bucket store are fixed in frostdb, it is a time to update frostdb here :)

**Comment by thorfour** [comment]
@arajkumar Thank you so much!

**Pull request merged**
